import { notFound } from 'next/navigation';
import { chapters } from '@/lib/data';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { FeatureCard } from '@/components/FeatureCard';
import { Sparkles, ClipboardList, BookCopy } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

export async function generateStaticParams() {
  return chapters.map((chapter) => ({
    chapterId: chapter.id,
  }));
}

export default function ChapterPage({ params }: { params: { chapterId: string } }) {
  const chapter = chapters.find(c => c.id === params.chapterId);

  if (!chapter) {
    notFound();
  }

  const features = [
    {
      title: 'AI Chapter Summary',
      description: 'Get a concise summary of the chapter generated by AI.',
      href: `/${chapter.id}/summary`,
      icon: <Sparkles className="h-6 w-6" />,
    },
    {
      title: 'Chapter Quiz',
      description: 'Test your knowledge with multiple-choice questions.',
      href: `/${chapter.id}/quiz`,
      icon: <ClipboardList className="h-6 w-6" />,
    },
    {
      title: 'Flashcards',
      description: 'Review key terms and definitions with interactive flashcards.',
      href: `/${chapter.id}/flashcards`,
      icon: <BookCopy className="h-6 w-6" />,
    },
  ];

  return (
    <div className="space-y-8">
      <div>
        <Button asChild variant="ghost" className="mb-4">
          <Link href="/">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Dashboard
          </Link>
        </Button>
        <h1 className="text-3xl md:text-4xl font-bold font-headline tracking-tight">{chapter.title}</h1>
        <p className="text-lg text-muted-foreground mt-2">{chapter.description}</p>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {features.map((feature) => (
          <FeatureCard key={feature.title} {...feature} />
        ))}
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="font-headline text-2xl">Chapter Content</CardTitle>
          <CardDescription>Read through the complete chapter text below.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="prose prose-stone dark:prose-invert max-w-none font-body text-base leading-relaxed">
            {chapter.content.split('\n\n').map((paragraph, index) => (
                <p key={index}>{paragraph}</p>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
